# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-10 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHOWS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='network',
            field=models.CharField(default='Add a network', max_length=80),
        ),
        migrations.AlterField(
            model_name='shows',
            name='description',
            field=models.TextField(default='Add a description'),
        ),
        migrations.AlterField(
            model_name='shows',
            name='title',
            field=models.CharField(default='Add a title', max_length=80),
        ),
    ]
