# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-10 18:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHOWS', '0002_auto_20190710_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
